name: Release

on:
  release:
    types: [published]

jobs:
  flatpak:
    name: Flatpak (Release, ${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-49
      options: --privileged
    strategy:
      matrix:
        include:
        - arch: x86_64
          runner: ubuntu-latest
        - arch: aarch64
          runner: ubuntu-24.04-arm
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.6
      with:
        bundle: almanah.flatpak
        manifest-path: dimmus.almanah.json
        cache-key: "flatpak-builder-${{ github.sha }}-${{ matrix.arch }}"
        arch: ${{ matrix.arch }}

  upload:
    name: Upload to Release
    runs-on: ubuntu-latest
    needs: flatpak
    permissions:
      contents: write
    steps:
    - name: Download Flatpak bundle (aarch64)
      uses: actions/download-artifact@v7
      with:
        name: almanah-aarch64.flatpak

    - name: Upload Flatpak to release (aarch64)
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mv almanah.flatpak 'almanah-${{ github.event.release.tag_name }}-aarch64.flatpak'
        gh release upload ${{ github.event.release.tag_name }} almanah-${{ github.event.release.tag_name }}-aarch64.flatpak --repo ${{ github.repository }}

    - name: Download Flatpak bundle (x86_64)
      uses: actions/download-artifact@v7
      with:
        name: almanah-x86_64.flatpak

    - name: Upload Flatpak to release (x86_64)
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mv almanah.flatpak 'almanah-${{ github.event.release.tag_name }}-x86_64.flatpak'
        gh release upload ${{ github.event.release.tag_name }} almanah-${{ github.event.release.tag_name }}-x86_64.flatpak --repo ${{ github.repository }}
